### ISSUE TITLE
Il controllo di integrità dei file riporta dei warning rispetto ai template modificati

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-matomo-theme#10]
Si dovrebbero aggiornare le dimensioni previste per i file modificati oppure escludere i file dal controllo di integrità.

`index.php?module=Installation&action=systemCheckPage&idSite=1&period=day&date=yesterday&showtitle=1&random=801`

**Comment by pdavide** [comment]
@Valair la pagina `index.php?module=Installation&action=systemCheckPage&idSite=1&period=day&date=yesterday` adesso mi restituisce un errore.

**Comment by Valair** [comment]
Resolved via #2
