### ISSUE TITLE
Layout header

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-matomo-theme#12]
Quando il nome dell'amministrazione è molto lungo anziché andare a capo salta a capo decentrando il layout.

<img width="1228" alt="Schermata 2019-12-04 alle 20 37 14" src="https://user-images.githubusercontent.com/9119858/70174878-fefc1580-16d5-11ea-9f24-7c5070eb511c.png">

**Comment by Valair** [comment]
Fixato con commit https://github.com/AgID/wai-matomo-theme/commit/deb6a777795377a7da4a1c74f4b5a8da906b8618
